#!/bin/bash

echo "====================================="
echo "Update follower configuration"
echo "====================================="
echo ""
echo "Copy one of these config files to darkwingdog:"
echo ""
echo "  scp follower-config.yaml paul@darkwingdog:~/follower-config.yaml"
echo "  # OR"
echo "  scp follower-config.json paul@darkwingdog:~/follower-config.json"
echo ""
echo "Then on darkwingdog, update the follower's configuration"
echo "to include BVN0 at 23.22.212.106:8080 as a known node."
echo ""
echo "This bypasses the bootstrap server and connects directly to BVN0."
echo ""
echo "After updating config, restart the follower with accman:"
echo "  accman restart app-follower"